language: r
cache: packages

r_packages:
  - covr
  - pkgdown
  - rcmdcheck

r:
  - release

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

after_success:
  - Rscript -e 'library(covr);codecov()'
